"""Portfolio & OMS Data Models"""
from __future__ import annotations
from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class AssetClass(str, Enum):
    EQUITY = "EQUITY"
    COMMODITY = "COMMODITY"
    FX = "FX"
    FIXED_INCOME = "FIXED_INCOME"
    CRYPTO = "CRYPTO"


class GeoTarget(BaseModel):
    """A physical location tied to an asset for monitoring."""
    id: str = Field(default_factory=lambda: __import__("uuid").uuid4().hex[:12])
    name: str  # e.g., "Tesla Shanghai Gigafactory"
    latitude: float
    longitude: float
    radius_km: float = 25.0
    target_type: str = "facility"  # facility, port, mine, pipeline, airfield, hq
    asset_ticker: str  # The stock ticker this geo-target maps to
    monitoring_sensors: list[str] = Field(default_factory=lambda: ["optical", "adsb"])
    active: bool = True
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Position(BaseModel):
    """A single portfolio position from the OMS."""
    ticker: str
    name: str
    side: PositionSide
    shares: int
    avg_entry_price: float
    current_price: Optional[float] = None
    pnl: Optional[float] = None
    asset_class: AssetClass = AssetClass.EQUITY
    sector: Optional[str] = None
    geo_targets: list[GeoTarget] = Field(default_factory=list)
    thesis: Optional[str] = None  # PM's natural language thesis
    thesis_created_at: Optional[datetime] = None


class Portfolio(BaseModel):
    """The fund's full portfolio loaded from OMS."""
    fund_name: str = "Sentinel Fund"
    positions: list[Position] = Field(default_factory=list)
    last_synced: datetime = Field(default_factory=datetime.utcnow)
    total_nav: float = 0.0  # Net Asset Value

    def get_position(self, ticker: str) -> Optional[Position]:
        for p in self.positions:
            if p.ticker.upper() == ticker.upper():
                return p
        return None

    def get_all_geo_targets(self) -> list[GeoTarget]:
        targets = []
        for p in self.positions:
            targets.extend(p.geo_targets)
        return targets

    @property
    def long_positions(self) -> list[Position]:
        return [p for p in self.positions if p.side == PositionSide.LONG]

    @property
    def short_positions(self) -> list[Position]:
        return [p for p in self.positions if p.side == PositionSide.SHORT]


class TradeProposal(BaseModel):
    """A proposed trade for user confirmation before position creation."""
    ticker: str
    name: str
    side: PositionSide
    suggested_shares: int = 100
    current_price: Optional[float] = None
    sector: Optional[str] = None
    thesis: str
    geo_targets: list[GeoTarget] = Field(default_factory=list)
    confidence: float = 0.0


class ThesisInput(BaseModel):
    """Natural language thesis from a PM."""
    text: str  # e.g., "Track Tesla's Shanghai output and correlate with export logistics"
    ticker: Optional[str] = None
    priority: str = "normal"  # low, normal, high, critical


class SensorTasking(BaseModel):
    """A sensor tasking request generated by the Orchestrator."""
    id: str = Field(default_factory=lambda: __import__("uuid").uuid4().hex[:12])
    geo_target: GeoTarget
    sensor_type: str  # optical, sar, adsb, ais, cctv, osm
    priority: int = 5  # 1=highest
    requested_at: datetime = Field(default_factory=datetime.utcnow)
    weather_blocked: bool = False
    fallback_sensor: Optional[str] = None
    status: str = "pending"  # pending, active, completed, failed
    result_data: Optional[dict] = None
